### ISSUE TITLE
reject bad input cases

### ISSUE THREAD

**Issue by wayslog** [niklasf/rust-btoi#3]
example input like:
```rust
assert!(btoi::btoi::<isize>(&*b"-").is_err());
```
but get an assert panic.

by the way, shall we use fuzz test tools to find out bad input?

example : 

https://fuzz.rs/book/cargo-fuzz.html

**Comment by niklasf** [comment]
Thanks for reporting. This was a pretty bad oversight. The existing fuzzing (https://github.com/niklasf/rust-btoi/blob/master/fuzz/fuzz_targets/) did not catch it, because parsing `-` did not panic (it incorrectly returned 0).

Fixed in analogy to std (https://doc.rust-lang.org/src/core/num/mod.rs.html#4823), and published as 0.4.1.

**Comment by wayslog** [comment]
Thanks you for fixed it.
